const fs=require('fs');const {execSync}=require('child_process');
const FILE='workflow.js';let src=fs.readFileSync(FILE,'utf8');
if(src.includes('/*continuity v2*/')){console.error('Deja patche.');process.exit(1);}
const A="  const msg=await anthropic.messages.create({model:'claude-sonnet-4-6',max_tokens:500,\n    messages:[{role:'user',content:'TikTok relationship coach women 20-40. Topic: \"'+topic+'\". Return ONLY valid JSON: {\"script\":\"Exactly '+words+' words. VIRAL TikTok script. STRICT RULES:\\n1. First sentence = THE HOOK (max 8 words). It MUST stop the scroll in under 1 second. Pick whatever is most viral for THIS topic: a shocking question, a brutal accusation, a forbidden secret, a bold contrarian claim, or a callout that makes her feel seen. Create an instant curiosity gap or emotional punch. No greeting, no warmup, no setup. Make it impossible to scroll past\\n2. Every sentence MAX 8 words. Cut ruthlessly.\\n3. Add [pause] after the hook and before the final punchline\\n4. Emotional, direct, no fluff. Each word earns its place.\\n5. No em dashes. English only.\",\"keywords\":[\"WORD1\",\"WORD2\",\"WORD3\",\"WORD4\"] — pick the 4 most emotionally charged shocking words only,\"caption_short\":\"Max 80 chars + emojis, punchy hook\",\"caption_long\":\"200-250 chars, develop the idea + call to action + emojis\",\"hashtags\":[\"t1\",\"t2\",\"t3\",\"t4\",\"t5\"] where the 5 tags are the MOST VIRAL generic TikTok hashtags (fyp, foryou, foryoupage, viral, trending, relatable) plus 1 topical one max, no hash symbol, lowercase, no spaces,\"reactions\":[{\"after\":\"exact sentence copied from the script\",\"type\":\"mhm|yeah|right|hmm\"}] choose EXACTLY 1 to 2 reactions max, placed right after the most impactful sentences (ideally near a [pause]), so it feels like an interviewer reacting; the \"after\" value MUST be copied verbatim from the script}'}]\n  });";
const B="  const __cont=/THIS IS PART [23]/i.test(topic); const __p3=/THIS IS PART 3/i.test(topic); /*continuity v2*/\n  const __rule1=__cont?('1. This is a DIRECT CONTINUATION of the SAME video, same person still talking. Do NOT use any hook. Do NOT greet, introduce, recap, summarize, or repeat ANY idea, sentence or phrasing from the earlier parts. Begin mid-thought with a NEW angle that deepens the SAME subject.'+(__p3?' End with ONE short call to action.':' No call to action.')):'1. First sentence = THE HOOK (max 8 words). It MUST stop the scroll in under 1 second. Pick whatever is most viral for THIS topic: a shocking question, a brutal accusation, a forbidden secret, a bold contrarian claim, or a callout that makes her feel seen. Create an instant curiosity gap or emotional punch. No greeting, no warmup, no setup. Make it impossible to scroll past';\n  const __rule3=__cont?'Add [pause] before the final punchline':'Add [pause] after the hook and before the final punchline';\n  const msg=await anthropic.messages.create({model:'claude-sonnet-4-6',max_tokens:500,\n    messages:[{role:'user',content:'TikTok relationship coach women 20-40. Topic: \"'+topic+'\". Return ONLY valid JSON: {\"script\":\"Exactly '+words+' words. VIRAL TikTok script. STRICT RULES:\\n'+__rule1+'\\n2. Every sentence MAX 8 words. Cut ruthlessly.\\n3. '+__rule3+'\\n4. Emotional, direct, no fluff. Each word earns its place.\\n5. No em dashes. English only.\",\"keywords\":[\"WORD1\",\"WORD2\",\"WORD3\",\"WORD4\"] — pick the 4 most emotionally charged shocking words only,\"caption_short\":\"Max 80 chars + emojis, punchy hook\",\"caption_long\":\"200-250 chars, develop the idea + call to action + emojis\",\"hashtags\":[\"t1\",\"t2\",\"t3\",\"t4\",\"t5\"] where the 5 tags are the MOST VIRAL generic TikTok hashtags (fyp, foryou, foryoupage, viral, trending, relatable) plus 1 topical one max, no hash symbol, lowercase, no spaces,\"reactions\":[{\"after\":\"exact sentence copied from the script\",\"type\":\"mhm|yeah|right|hmm\"}] choose EXACTLY 1 to 2 reactions max, placed right after the most impactful sentences (ideally near a [pause]), so it feels like an interviewer reacting; the \"after\" value MUST be copied verbatim from the script}'}]\n  });";
const c=src.split(A).length-1;
if(c!==1){console.error('Ancre = '+c+' (attendu 1). Annule, rien ecrit.');process.exit(1);}
src=src.split(A).join(B);
fs.writeFileSync('workflow.patched.js',src);
try{execSync('node --check workflow.patched.js',{stdio:'pipe'});}
catch(e){console.error('Syntaxe KO.');console.error(e.stderr?e.stderr.toString():e.message);process.exit(1);}
fs.copyFileSync(FILE,FILE+'.precontinuity');fs.renameSync('workflow.patched.js',FILE);
console.log('Patch continuite v2 (parties 2/3 = vraie suite, sans hook ni recap) applique.');
