const fs=require('fs');const {execSync}=require('child_process');
const FILE='telegram_bot.js';let src=fs.readFileSync(FILE,'utf8');
if(src.includes('// suivi MM')){console.error('Deja patche. Annule.');process.exit(1);}
const A1="  scriptBuf='';collectScript=false;\n  const args=[path.join(BASE,'workflow.js')];";
const B1="  scriptBuf='';collectScript=false;\n  let mmPing=null; // suivi MM\n  const args=[path.join(BASE,'workflow.js')];";
const A2="      if(line.match(/Audio Part|ElevenLabs/i))await send('\u{1F399} Audio... [\u2588\u2588\u2588\u2588\u2591\u2591\u2591\u2591\u2591\u2591] 35%').catch(()=>{});\n      if(line.match(/\u{1F3B2} Random look:/i))await send(line).catch(()=>{});\n      if(line.match(/Lipsync Part/i))await send('\u{1F3AC} Lipsync... [\u2588\u2588\u2588\u2588\u2588\u2588\u2591\u2591\u2591\u2591] 60%  (2-5 min)').catch(()=>{});\n      if(line.match(/Rendering Part/i))await send('\u2728 Rendering... [\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2591\u2591] 85%').catch(()=>{});\n      if(line.match(/Saved:/i))await send('\u2705 Done! [\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588] 100%').catch(()=>{});";
const B2="      if(line.match(/\u{1F4DD} Script/i))await send('\u{1F4DD} \u00c9tape 2/6 \u2014 \u00c9criture du script...').catch(()=>{});\n      if(line.match(/Audio Part|ElevenLabs/i))await send('\u{1F399} \u00c9tape 3/6 \u2014 G\u00e9n\u00e9ration de la voix...').catch(()=>{});\n      if(line.match(/\u{1F3B2} Random look:/i))await send(line).catch(()=>{});\n      if(line.match(/Preparing avatar/i))await send('\u{1F5BC} \u00c9tape 4/6 \u2014 Pr\u00e9paration de l\u2019avatar...').catch(()=>{});\n      if(line.match(/Lipsync Part/i)){\n        await send('\u{1F3AC} \u00c9tape 5/6 \u2014 Lipsync en cours...\\n\u23F3 \u00c7a prend 2 \u00e0 5 minutes, patiente.').catch(()=>{});\n        if(mmPing)clearInterval(mmPing);\n        mmPing=setInterval(()=>{ send('\u23F3 Lipsync toujours en cours...').catch(()=>{}); },60000);\n      }\n      if(line.match(/Rendering Part/i)){\n        if(mmPing){clearInterval(mmPing);mmPing=null;}\n        await send('\u2728 \u00c9tape 6/6 \u2014 Montage final...').catch(()=>{});\n      }";
const A3="      // Video saved\n      if(line.includes('Saved:')){\n        const m=line.match(/Saved:\\s*(.+\\.mp4)/);\n        if(m&&fs.existsSync(m[1].trim())){\n          setTimeout(async()=>{\n            await send('\u{1F4F1} <b>Sending video to Telegram...</b>').catch(()=>{});\n            await sendVid(m[1].trim()).catch(async()=>{\n              await send('\u26A0\uFE0F Video too large \u2014 check iCloud \u2192 podcast-outputs').catch(()=>{});\n            });\n          },3000);\n        }\n      }";
const B3="      // Video saved : workflow imprime \"Part N: chemin.mp4\"\n      {\n        const m=line.match(/\u2705 Part \\d+:\\s*(.+\\.mp4)/)||line.match(/Saved:\\s*(.+\\.mp4)/);\n        if(m&&fs.existsSync(m[1].trim())){\n          if(mmPing){clearInterval(mmPing);mmPing=null;}\n          const vp=m[1].trim();\n          await send('\u2705 Vid\u00e9o pr\u00eate ! Envoi en cours...').catch(()=>{});\n          setTimeout(async()=>{\n            await sendVid(vp).catch(async()=>{\n              await send('\u26A0\uFE0F Vid\u00e9o trop lourde pour Telegram \u2014 voir iCloud \u2192 podcast-outputs').catch(()=>{});\n            });\n          },2000);\n        }\n      }";
const A4="  proc.on('close',()=>{\n    proc=null;state='idle';";
const B4="  proc.on('close',()=>{\n    if(mmPing){clearInterval(mmPing);mmPing=null;}\n    proc=null;state='idle';";
function rep(a,b,l){const c=src.split(a).length-1;if(c!==1){console.error('Ancre '+l+' = '+c+' (attendu 1). Annule.');process.exit(1);}src=src.split(a).join(b);}
rep(A1,B1,'1');rep(A2,B2,'2');rep(A3,B3,'3');rep(A4,B4,'4');
fs.writeFileSync('telegram_bot.patched.js',src);
try{execSync('node --check telegram_bot.patched.js',{stdio:'pipe'});}
catch(e){console.error('Syntaxe KO.');console.error(e.stderr?e.stderr.toString():e.message);process.exit(1);}
fs.copyFileSync(FILE,FILE+'.preprogress');fs.renameSync('telegram_bot.patched.js',FILE);
console.log('Patch progress applique. Sauvegarde : '+FILE+'.preprogress');
